version: 0.1.0
name: anaissi-data-strategy
builds:
  - src: .
    use: static
    config:
      publish: dist
      buildCommand: npm install && npm run build
      routes:
        - src: /*
          dest: /index.html
